"""
Game state.

This module defines the data structures used to store the current
state of an interactive narrative playthrough.
"""

from dataclasses import dataclass, field


@dataclass(slots=True)
class GameState:
    """
    Represents the current state of the interactive narrative.

    The game state stores all information required to continue the
    story across multiple turns.

    Attributes:
        retrieval_mode:
            Retrieval backend currently used by the application.
            Typical values are "rag" and "graph".

        current_scene:
            Identifier of the currently active scene.

        turn:
            Number of generated story turns.

        history:
            Chronological record of the player's decisions.

        generated_story:
            Story segments generated by the language model.

        finished:
            Indicates whether the current playthrough has ended.
    """

    retrieval_mode: str

    current_scene: int | None = None

    turn: int = 0

    history: list[dict] = field(default_factory=list)

    generated_story: list[str] = field(default_factory=list)

    finished: bool = False

    def clear(self) -> None:
        """
        Reset the game state.

        This method clears all generated content while preserving the
        selected retrieval backend.
        """

        self.current_scene = None
        self.turn = 0
        self.history.clear()
        self.generated_story.clear()
        self.finished = False

    @property
    def story(self) -> str:
        """
        Return the complete generated story.

        Returns:
            str:
                Complete story generated during the current
                playthrough.
        """

        return "\n\n".join(self.generated_story)
